server:
  error:
    include-message: never
    include-stacktrace: never

spring:
  messages:
    encoding: UTF-8
    basename: messages/api_error, messages/config_error
  main:
    allow-bean-definition-overriding: true

  jackson:
    deserialization:
      read-date-timestamps-as-nanoseconds: false
    serialization:
      write-dates-as-timestamps: false

bestclick:
  logging:
    exception:
      business: true
      server: true